// Code generated by "stringer -linecomment -type LogLevel ./pkg/logger"; DO NOT EDIT.

package logger

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[FATAL-0]
	_ = x[ERROR-1]
	_ = x[WARNING-2]
	_ = x[INFO-3]
	_ = x[DEBUG-4]
	_ = x[TRACE-5]
}

const _LogLevel_name = "[FATA][ERRO][WARN][INFO][DEBU][TRAC]"

var _LogLevel_index = [...]uint8{0, 6, 12, 18, 24, 30, 36}

func (i LogLevel) String() string {
	if i < 0 || i >= LogLevel(len(_LogLevel_index)-1) {
		return "LogLevel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _LogLevel_name[_LogLevel_index[i]:_LogLevel_index[i+1]]
}
